services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    restart: always
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/notification_app
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "512MB"
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/postgresql:/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "256MB"
  database:
    image: postgres:17.0-alpine
    container_name: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=notification_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - 'postgres'
      - '-c'
      - 'effective_cache_size=256MB'
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "256MB"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql

  messaging:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
      - RABBITMQ_DEFAULT_VHOST=/
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "256MB"