CREATE TABLE MESSAGES (
  MESSAGE_ID UUID PRIMARY KEY,
  TENANT_ID UUID NOT NULL,
  CONTENT JSONB NOT NULL,
  RECEIVED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ACKED BOOLEAN NOT NULL DEFAULT FALSE,
  ACKED_AT TIMESTAMP NULL
);