server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /api/notification-socket

scheduler:
  pool-size: 1

spring:
  application:
    name: notification-socket
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/notification-app
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${NOTIFICATION_APP_DATABASE_HOST:jdbc:postgresql://localhost:5432/notification_app}
    username: ${NOTIFICATION_APP_DATABASE_USER:postgres}
    password: ${NOTIFICATION_APP_DATABASE_PASSWORD:postgres}
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev
    virtual-host: /
    connection-timeout: 5000
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: manual
  data:
    redis:
      host: localhost
      timeout: 5000
      port: 6379